CREATE TABLE `attachfile` (
	`FILE_GROUP` INT(10) NOT NULL COMMENT '파일그룹',
	`FILE_ORDER` INT(10) NOT NULL COMMENT '파일순서',
	`FILE_PATH` VARCHAR(400) NOT NULL COMMENT '파일경로',
	`FILE_NAME_ORG` VARCHAR(400) NOT NULL COMMENT '원본파일명',
	`FILE_NAME_SAV` VARCHAR(400) NOT NULL COMMENT '저장파일명',
	`FILE_SIZE` VARCHAR(50) NOT NULL COMMENT '파일크기',
	`FILE_EXTENSION` VARCHAR(10) NOT NULL COMMENT '파일 확장자',
	PRIMARY KEY (`FILE_GROUP`, `FILE_ORDER`)
)
COMMENT='첨부파일'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
