CREATE TABLE `board` (
	`BOARD_NAME` VARCHAR(100) NOT NULL COMMENT '게시판명',
	`BOARD_NO` INT(11) NOT NULL COMMENT '게시판 번호',
	`TITLE` VARCHAR(100) NOT NULL COMMENT '제목',
	`CONTENTS` LONGTEXT NOT NULL COMMENT '내용',
	`REPLY_GROUP` INT(11) NOT NULL COMMENT '답글 그룹',
	`REPLY_STEP` INT(11) NOT NULL COMMENT '답글 순서',
	`REPLY_DEPTH` INT(11) NOT NULL COMMENT '답글  깊이',
	`FILE_GROUP` INT(11) NOT NULL COMMENT '첨부파일번호',
	`REG_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
	`REG_USER` VARCHAR(15) NOT NULL COMMENT '생성자',
	`MOD_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
	`MOD_USER` VARCHAR(15) NOT NULL COMMENT '수정자',
	PRIMARY KEY (`BOARD_NAME`, `BOARD_NO`)
)
COMMENT='게시판'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
